site_name: WasteNot Documentation

nav:
  - Getting Started: index.md
#  - Install: install.md
  - API Features:
      - Forecasting: forecast_example.md  
      - Backcasting: backcast_example.md        
  - Code Examples:
      - Python: 
          - Visualise Forecast: forecast_visualise.ipynb
  - Notebook page: notebook.ipynb

  
theme:
  name: material

plugins:
  - mkdocs-jupyter


